### ISSUE TITLE
/coSpaceBulkSyncs using wrong @XmlRootElement(name = "cospaceBulkSyncs")

### ISSUE THREAD

**Issue by rbeals60** [ciscocms/apiary#1]
IAW Cisco Meeting Server Cisco Meeting Server Release 2.4 and later API Reference Guide April 24, 2019
 
Section 6.8.5  (page 57)  Retrieving the bulk sync operations GET method on "/coSpaceBulkSyncs " node.
 
Response is structured as a top-level <coSpaceBulkSyncs total=“N”/> tag with potentially multiple <coSpaceBulkSync> elements within it.

However the response for the service is:

<?xml version="1.0"?>
<cospaceBulkSyncs total="0"></cospaceBulkSyncs>
 
The issue is the S in Space is not capitalized in the XML message that is returned.
Thus the framework can not map this to the expected token since it uses a case sensitive string match.
 
So if you follow the guidance of the documentation then the message can not be consumed.

**Comment by dstaudt** [comment]
Looks like the example response snippet was lost, should be:

`<?xml version="1.0"?>
<cospaceBulkSyncs total="0"></cospaceBulkSyncs>`

**Comment by ryanquinlan** [comment]
@rbeals60 We are not case sensitive on the CMS API side of things. Given that, it should be possible then for you to make your call to `cospaceBulkParameterSets` which then will match the response of the same.

If that works for you, let me know and I'll file a docs change for this. Will be easier than changing the API implementation I think.

**Comment by ryanquinlan** [comment]
Closing this as a documentation defect has been raised.
